version: '3'
services:
  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
    networks:
      - app-network

  cart-service:
    build: ./cart-service
    ports:
      - "3002:3002"
    depends_on:
      - product-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
